### PR TITLE
UI interface position change

### PR DESCRIPTION
**Pull request by GoldenStone929**
I have edited HTML, CSS, to make buttons placed evenly with same width and same height, 
Since we have 5 buttons, I have placed "about us" and "guidance" in the same dropDown, it shows when hover.

I have edited <header><header> and <main><main> position because it was in wrong order.

I have edited Js file and now background color change works

### CODE REVIEW

**Review by will-loves-coding82 — COMMENTED** [review]
please resolve the eslint errors.

**Comment by ZhaoyuTina** [comment]
Looks good remember to replace those Chinese placeholders

**Review by ZhaoyuTina — CHANGES_REQUESTED** [review]
Please fix those ESLint errors

**Comment by GoldenStone929** [comment]
Hi, these are the notes and some comments for myself, I will need to edit
more on css part. I’ll clear comments once it’s all done.

Zhaoyu Zhang ***@***.***>于2022年11月29日 周二下午2:33写道：

**Comment by GoldenStone929** [comment]
I’ll check it soon

Zhaoyu Zhang ***@***.***>于2022年11月29日 周二下午2:35写道：

**Review by hurl365 — CHANGES_REQUESTED** [review]
The <title> of the website seems to be “单位转换,” which we might wanna change into something to do with ProForce?

**Review by will-loves-coding82 — APPROVED** [review]
lol yeah we needed to remove these characters

**Review by hurl365 — APPROVED** [review]
Tests are now passing. I manually checked add and edit, and these two are working well. Well done!

**Review by ZhaoyuTina — APPROVED** [review]
Awsome!

**Pull request merged**
