### PR TITLE
Features/import upload fix

### LINKED ISSUE #64: [Back End] Upload field not clearing itself in index.js
### **index.js**
**prerequisite**
NA

**Insert the problem**
The upload field is not clearing itself after the import is done unless you reload the page manually. It won't allow you to upload the same coffeecard again (two same cards in a row), which technically should be legal.

**Insert the problematic lines' line numbers**
NA

**insert the problematic program/code**
```
    importButton.addEventListener("change", (event) => {
        console.log("import clicked");  // DELETE: for test
        let importFile = event.target.files[0];    // Get the file uploaded by user
        // console.log(importFile.name);    // DELETE: for test

        // Basic type-check for the uploaded file
        if(importFile.type != "application/json") {
            console.error("Wrong file type: must import a JSON file!");
            return;
        }

        let reader = new FileReader();  // Reader to read the imported file content

        reader.addEventListener("load", () => {
            let fileText = JSON.parse(reader.result);
            // console.log(fileText);  // DELETE: for test

            // Update local cards
            let coffeeCards = getCoffeeCardsFromStorage();
            coffeeCards.push(fileText);
            saveCoffeeCardsToStorage(coffeeCards);

            // Update gallery with new card
            addCoffeeCardsToDocument(coffeeCards);

            // Update current_card_id field
            localStorage.setItem('current_card_id', coffeeCards.length - 1);

            // FIXME: Upload field is not clearing itself after each upload
        }, false);
        
        // Reader reads the file as text if valid
        if (importFile) {
            reader.readAsText(importFile);
        }
    })
```
**Resources**
Please put any relevant resources that can help resolve this issue here.

### PR DESCRIPTION
**Pull request by JSalazar026**
Resolves #64 and #50 

Changes made:
- Replaced the input HTML element for file uploads with a button that could be styled and would call the input element when the button was clicked. The button was styled similarly.
- Reset the files uploaded so that users could upload the same file multiple times in a row
- Added a check so that if the user was adding/editing a card, then no other events such as share, delete, would fire.

### CODE REVIEW

**Review by will-loves-coding82 — APPROVED** [review]
I tested out everything you mentioned and it works as intended. Nice work. I will approve this and merge into main.

**Review by hurl365 — CHANGES_REQUESTED** [review]
Unfortunately, the automated tests with "npm run test" are all failing. Please double check the functionality of the program at this point. Please change the start of the user_flow_test.js to the following before testing:
```
beforeAll(async () => {
      // Now using Github Page URL. Feel free to change back to Live Server URL for manual testing!
      await page.goto('http://127.0.0.1:5501/source/index.html');
    });
```

**Comment by hurl365** [comment]
Please do not refresh the page and use the function addCoffeeCardsToDocument(), as it will automatically remove all existing cards from the page and add new ones. This way is extremely inefficient with large amount of cards and we will have to re-write all the E2E tests.

**Review by will-loves-coding82 — COMMENTED** [review]
There are some syntax errors. Please address them
image

Also I wil fix the automated tests in a new branch since that is a separate issue

**Comment by hurl365** [comment]
This merge is intending resolve #47 and #69.

**Comment by will-loves-coding82** [comment]
Also it should be noted that the code to disable buttons when opening the form was interfering with the add and edit functionalities so they've been commented out for those. I think there might be a better way to do this which was posted about in #50

**Comment by will-loves-coding82** [comment]
I will be adding a few changes after this to get jest to run in github actions

**Comment by hurl365** [comment]
resolve #69

**Pull request merged**
