### PR TITLE
Merge Edit Button Feature into Main

### PR DESCRIPTION
**Pull request by hurl365**
- [ ] Check style and commenting (no new modules added, so comments are limited)
- [ ] Manually test the new feature

### CODE REVIEW

**Review by will-loves-coding82 — COMMENTED** [review]
So i tested this out and something I caught was that you were hard coding the card-to-edit's innerHTML whenever the user saved their changes after editing a card. For some reason, the color level would never change as it would always display "Light" even though in local Storage it did change. So I recommend commenting that portion out and just using the predefined addCofeeCardsToDocument(coffeeCards) to handle this for you easily. It should update the page automatically as well rather than having to manually refresh the page by yourself.
```
       else if (isEditing) {
            // update the card in the array
            console.log(coffeeCardObject);
            coffeeCards[current_edit_id] = coffeeCardObject;
            console.log("form is editing card at index: " + current_edit_id);
            // save to storage and update the page
            saveCoffeeCardsToStorage(coffeeCards);
            /*
            let all_coffee_cards = document.querySelectorAll('coffee-card');
            let card_to_edit = all_coffee_cards[current_edit_id];
            card_to_edit.innerHTML =
            `
            <header>
                 <h3><slot name="date" />${coffeeCardObject["str_drink_name"]}</h3>
                 <h4>${coffeeCardObject["time_purchase_date"].toUpperCase()}</h4>
                 <img id="share_button" alt = "share icon" src = "./assets/images/share-icon.png" ></img>
     
            </header>
     
             <section class="info">
               <p><slot name="location" />Location: ${coffeeCardObject["str_purchase_location"]}</p>
               <p><slot name="brew_style" />Brew Method: ${coffeeCardObject["str_brew_style"]}</p>
               <p><slot name="drink_type">Serving Type: ${coffeeCardObject["str_drink_type"]}</p>
               <p><slot name="color">Color Level: ${coffeeCardObject["int_dropdown_color"]}</p>
               <p id="current_card_id" value="${coffeeCardObject["current_card_id"]}" hidden></p>
             </section>
             <button class = "toggle_edit" >Edit</button>
             `;
             */
        }
        
        //reset the coffee card's image to the default one, at index 0
        reset_image_id();
        isEditing = false;
        closeForm();
        addCoffeeCardsToDocument(coffeeCards);
```
Also one more thing. Can you explain why you reset the image id when editing?

**Comment by hurl365** [comment]
This commit should be able to resolve #52

**Review by will-loves-coding82 — APPROVED** [review]
The editing functionality works as expected. Of course we will need to implement jest unit tests later next week to test it thoroughly. Nice job!

**Review by JSalazar026 — COMMENTED** [review]
I spent a good amount of time testing this code - as far as I can see, this code doesn't have any flaws. The style isn't consistent as flagged by the linter, but we can use proper style later. Great job for figuring out the issues that stumped us.

**Pull request merged**
