### PR TITLE
Features/main page design2

### LINKED ISSUE #55: [New Feature] Main page background color change as user's preferrence
### **[insert feature name here]**
**prerequisite**
List the prerequisites of this issue if applies.
Link to any existing issues that must be solved before this one.

**description**
edit HTML, CSS, and Javascript file to add the new feature "background-color change", as a dropdown list

**Insert the steps to complete to fully implement this feature**
- [ ] step 1: HTML -> body --> header --> section --> <select><select> option
- [ ] step 2: CSS -> design
- [ ] step 3: javascript

**Resources**
Please put any relevant resources that can help resolve this issue here.

### LINKED ISSUE #56: [New Feature] About Us (team 14)
### **[About Us]**
**prerequisite**
List the prerequisites of this issue if applies.
Link to any existing issues that must be solved before this one.

**description**
A block that user can click that opens the new page that contains all the information about team 14,
it contains a lot of feature and informations in that individual HTML page

**Insert the steps to complete to fully implement this feature**
- [ ] step 1: a individual HTML file and is linked to index.main
- [ ] step 2: page design
- [ ] step 3: features

**Resources**

### LINKED ISSUE #57: Main page button Css
### **[insert issue name here]**
**prerequisite**
N/A
**description**
Since background color change feature and new button has been added, and some will be added (import) button,
we currently have 5 buttons on the page and we need to make it even in position and style them the same. Even thought there are links, buttons, we need to make it look similar

So in css, things like:
text-decoration
 -webkit-text-stroke:
border-radius
position
font
icon
etc 
needs to be edited

**Insert the steps to complete to fully implement this feature**
make sure it looks the same

**Resources**
Please put any relevant resources that can help resolve this issue here.

### LINKED ISSUE #66: Merge MainPage design
**description**
issue 55,56,57 
we need to merge this asap

### PR DESCRIPTION
**Pull request by GoldenStone929**
resolved #55 
resolved #56 
resolved #57 
to resolve #66

### CODE REVIEW

**Review by hurl365 — APPROVED** [review]
This change is very artistic. The about us page looks really cool. Good job!

**Comment by will-loves-coding82** [comment]
Good work. However it is a bit messy so I can help clean up the look of the page

**Comment by hurl365** [comment]
The available tests are all passing with this version as well. Well done!

**Review by will-loves-coding82 — COMMENTED** [review]
I will approve these changes. However I will help clean up the look of the page

**Pull request merged**
