### PR TITLE
Implemented Image Switching on Coffee Card

### LINKED ISSUE #14: Work on Popup Form
- [x] #17
- [x] #15
- [x] implement functionality to switch between images for the photo of the coffee
- [ ] add necessary "required" attributes to input tags that need it

### PR DESCRIPTION
**Pull request by hurl365**
Resolved #14 and #33 . Please manually check style and test the functionalities before merge.

### CODE REVIEW

**Review by JSalazar026 — APPROVED** [review]
I would like to see some comments or documentation somewhere indicating what coffee-picture 0, 1, 2, and 3 correspond to for future reference. This also helps preserve the elegance of this implementation.
I also notice the arrows for switching the images are inside the label "switch image functionality". I assume they are not supposed to be there. In case I'm wrong, disregard this comment. Otherwise, just create an issue in GitHub projects to address this bug. I think it'll be pretty easy to change

Summary: Good style and I checked to make sure this solution works. Everything's good. I made my comments above but I'll approve this PR since the code is maintainable and clear.

**Comment by will-loves-coding82** [comment]
I reviewed the code and I appreciate the extensive documentation and adherence to style. I will approve this and once this pr gets merged I will also add my changes to the linting tests

**Review by will-loves-coding82 — COMMENTED** [review]
I reviewed the code and I appreciate the extensive documentation and adherence to style. I will approve this and once this pr gets merged I will also add my changes to the linting tests

**Review by will-loves-coding82 — APPROVED** [review]
I reviewed the code and I appreciate the extensive documentation and adherence to style. I will approve this and once this pr gets merged I will also add my changes to the linting tests

**Review by ZhaoyuTina — APPROVED** [review]

**Pull request merged**
